### ISSUE TITLE
Matching Sex for 'unknown' Reported Sex

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_somalier_relate2multiqc#2]
If Reported Sex is unknown then Matching Sex should always be NA, since looking for a match doesn't make sense. This can then be formatted appropriately in MultiQC, rather than being flagged as a mismatch/fail

![image](https://user-images.githubusercontent.com/8166553/113265142-b190b800-92cb-11eb-90fe-7530180110a0.png)

**Comment by Aisha-D** [comment]
fixed in PR #4
